### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by hvdmeer** [dgrammatiko/Joomla.gzip.control#2]
I installed the plugin, put it as high as possible in the ordering but Facebook still can't scrape my site. Are there any other tips on how I can make your plugin work on my site?

**Comment by dgrammatiko** [comment]
@hvdmeer Sorry for the late response. Please make sure that cache plugin is disabled!

**Comment by RemcoJanssen** [comment]
Hi there, I have the same issue, and disabling cache does fix it, but... I need caching on this site. Is there another suggestion you can make?

**Comment by dgrammatiko** [comment]
@RemcoJanssen Disabling the cache plugin does NOT mean that you will totally disable caching.
There is a confusion what this plugin does and if this is needed for most sites. So:
Cache Plugin is a way to make your site STATIC. That means that most of the code, including this plugin, will never execute after the page is rendered for at least one time. 
Now this is something most people don’t really want to enable on their sites and is irrelevant to the other caching found in global config. 
To cut it short: adjust your cache in global config and disable cache plugin, is the best option for DYNAMIC sites. Now if you want a static site I guess you have to work it so that the rendered pages don’t exceed 40kb
Hope this clears out things

**Comment by RemcoJanssen** [comment]
@dgt41 Thank you for explaining, I was just reading about caching and I am going to see how the site reacts with the plugin disabled. Scraping works fine now, thanks to your plugin!

**Comment by Diarmiud** [comment]
Hello,
thank you for the explanation. But my site-speed with Plugin-Cache "On" is significant faster and all the other things on my site work fine. Online Gzip, I mean Facebook-Share, doesn't work. :-(

So: Is there any possibility to have a good Facebook-Share with Plugin-Cache=On? 

Thanks a lot
Peter

**Comment by dgrammatiko** [comment]
@Diarmiud yes, but you need to make sure that your pages weight is less than 40kb. Most probably another template will help you achieve this goal!
